mob menu вирівняв текст, додав бордер
IrynaDidkivska/ice-cream pull request #10
Opened 2022-05-08 12:27 UTC by YuriiLeo

+ виправив назви класів

2022-05-08 13:12 UTC, IrynaDidkivska requested changes

2022-05-08 13:12 UTC, IrynaDidkivska commented on src/sass/components/_mobile-menu.scss
>      line-height: 1.3;
а можеш будь ласка стилізувати  посилання і кнопки через  міксин?
@include fonts(14px, 1.3);
  font-weight: 700;
  color: $main-link-color;

2022-05-08 13:12 UTC, IrynaDidkivska commented on src/sass/components/_mobile-menu.scss
>      color: #D41443;
і тут кнопки через змінні:
color: $ligth-mode-btn;
background-color: $ligth-mode-btn-bgc;

2022-05-08 21:00 UTC, YuriiLeo commented on src/sass/components/_mobile-menu.scss
>      line-height: 1.3;
змінив і наче зробив пул

2022-05-09 04:16 UTC, IrynaDidkivska approved these changes

2022-05-09 04:16 UTC, merged